[package]
name = "AdventOfCode2021"
version = "1.0.0"
edition = "2018"

[profile.release]
debug = true

[dependencies]
retain_mut = "0.1.5"
regex = "1.5.4"
ahash = "0.7.6"
keyed_priority_queue = "0.4.1"
